### PR TITLE
Feature: Added 3 ratings components

### PR DESCRIPTION
**Pull request by poojakelkar**
- Added Rating component

Live link: https://awesome-almeida-cbb787.netlify.app/

### CODE REVIEW

**Review by tushargoyal812 — COMMENTED** [review]
i think no change needed looks good to merge.

**Comment by poojakelkar** [comment]
Thanks

**Review by shobit1337 — APPROVED** [review]
Looks good to me!

**Comment by poojakelkar** [comment]
Thanks

**Pull request merged**
